ALTER TABLE TB_PATIO
    ADD CONSTRAINT fk_patio_usuario FOREIGN KEY (id_usuario) REFERENCES TB_USUARIO(id_usuario);

ALTER TABLE TB_MOTO
    ADD CONSTRAINT fk_moto_status FOREIGN KEY (id_status) REFERENCES TB_STATUS_MOTO(id_status);

ALTER TABLE TB_MOTO
    ADD CONSTRAINT fk_moto_patio FOREIGN KEY (id_patio) REFERENCES TB_PATIO(id_patio);

ALTER TABLE TB_ANTENA
    ADD CONSTRAINT fk_antena_patio FOREIGN KEY (id_patio) REFERENCES TB_PATIO(id_patio);

ALTER TABLE TB_MOTO_TAG
    ADD CONSTRAINT fk_mototag_moto FOREIGN KEY (id_moto) REFERENCES TB_MOTO(id_moto);

ALTER TABLE TB_MOTO_TAG
    ADD CONSTRAINT fk_mototag_tag FOREIGN KEY (id_tag) REFERENCES TB_TAG(id_tag);
